version: '3.8'

services:
  db:
    container_name: sales_db
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - 5432:5432

  sales-api:
    container_name: sales-api
    image: sales-api:1.0
    ports:
      - 3000:3000 # CRUD API
      - 4000:4000 # DEBUG API
    depends_on:
      - db

#  metrics:
#    container_name: metrics
#    networks:
#      - shared-network
#    image: metrics-amd64:1.0
#    ports:
#      - 3001:3001 # EXPVAR API
#      - 4001:4001 # DEBUG API
#    depends_on:
#      - sales-api